# AutoSavePlus Configuration
# (c) 2013 dmulloy2

# Delay in minutes between saves
delay: 15

# Messages broadcast to the server when save occurs
start: '&d[Server] **Saving all worlds and player data**'
finish: '&d[Server] **Save Complete!**'

# Worlds to save
worlds:
- "*"
  
# Extra output to console
debug: false

# Log the saving of players and worlds (does not affect broadcasts)
logAllWorlds: true