# AutoSavePlus Configuration
# (c) 2013 dmulloy2

# Delay in minutes between saves
delay: 15

# Messages broadcast to the server when save occurs
# This supports color codes
start: '&d[Server] **Saving all worlds and player data**'
finish: '&d[Server] **Save Complete!**'

# Worlds to save
# If '*' is an element, all worlds are saved
worlds:
- "*"

# Extra output to console
debug: false

# Logs each individual world as it's saved
logAllWorlds: false