name: AutoSavePlus
main: net.dmulloy2.autosaveplus.AutoSavePlus
version: ${project.version}${project.build.number}
author: dmulloy2
description: Simple AutoSave plugin allowing the saving of individual worlds, defined in the configuration.
commands:
  asp:
    description: AutoSavePlus root command
    aliases: [autosave, autosaveplus]
    usage: /<command> <args>
permissions:
  autosaveplus.*:
    description: Allows access to all AutoSavePlus commands
    children:
      asp.save: true
      asp.reload: true
  autosaveplus.save:
    description: Allows a player to force a world save
    default: false
  autosaveplus.reload:
    description: Allows a player to reload the plugin
    default: false